#!/usr/bin/env python3
"""
reorganize.py  —  Restructure the flat Seller-MS Flask app into a modular
`modules/<area>/` layout WITHOUT breaking the running application.

WHAT IT DOES (idempotent, safe to re-run):
  1. Creates `modules/<area>/` packages, each with:
        __init__.py, routes.py (the moved route file), service.py,
        validation.py, api.py  (stubs generated where none existed),
        templates/<area>/...   (the moved templates for that blueprint).
  2. Gives every blueprint an explicit `template_folder` so existing
     `render_template('<area>/xxx.html')` calls resolve unchanged.
  3. Creates the per-child folders required by the target spec
     (e.g. purchase/purchase_order/) each with the standard file set:
        form/list/view/create/edit/print/report.html
     Existing templates are reused; missing ones get real boilerplate stubs.
  4. Rewrites imports in app.py and database/routes/__init__.py to the new
     module paths.
  5. Leaves models.py / forms.py at project root (imported absolutely).

A full backup is written to  _backup_before_reorg/  before anything moves.
Run:  python reorganize.py         (apply)
      python reorganize.py --dry   (print plan only)
"""
import os, sys, shutil, re

ROOT = os.path.dirname(os.path.abspath(__file__))
DRY  = '--dry' in sys.argv

def log(*a):
    print(*a)

# ── AREA MAP ────────────────────────────────────────────────────────────
# area -> (route_file_stem, blueprint_var, existing_template_subdir_or_None,
#          [child folder names per target spec])
AREAS = {
    'seller': dict(routes=['sellers', 'seller_doc', 'banks'],
                   tpl_subdirs=['sellers', 'seller_documents', 'banks'],
                   children=['seller', 'documents', 'bank', 'warehouse']),
    'buyer':  dict(routes=['buyer_doc'],
                   tpl_subdirs=['buyer_documents'],
                   children=['buyer', 'documents', 'department', 'bank']),
    'vendor': dict(routes=['vendor_doc'],
                   tpl_subdirs=['vendor_documents'],
                   children=['registration', 'documents', 'bank']),
    'employee': dict(routes=['employees', 'employee_import',
                             'work_allocations', 'allowances', 'allowance_types',
                             'department_locations', 'professions'],
                     tpl_subdirs=['employees', 'work_allocations'],
                     children=['employee', 'work_allocation', 'bank',
                               'allowance', 'allowance_type']),
    'payroll': dict(routes=['payroll'],
                    tpl_subdirs=['payroll'],
                    children=['salary_sheet', 'salary_consolidation',
                              'payroll_process', 'reports']),
    'purchase': dict(routes=['purchase'],
                     tpl_subdirs=['purchase'],
                     children=['purchase_request', 'purchase_quotation',
                               'purchase_order', 'goods_receipt_note',
                               'purchase_invoice', 'goods_return_request',
                               'purchase_debit_memo', 'purchase_tax_code']),
    'sales': dict(routes=['sales'],
                  tpl_subdirs=['sales'],
                  children=['sales_request', 'sales_quotation', 'sales_order',
                            'goods_delivery_note', 'sales_invoice',
                            'goods_return_request', 'sales_credit_memo',
                            'sales_tax_code']),
    'financial_year': dict(routes=['financial'],
                           tpl_subdirs=['financial'],
                           children=[]),
    'chart_of_accounts': dict(routes=['coa'],
                              tpl_subdirs=['coa'],
                              children=['level1', 'level2', 'level3',
                                        'level4', 'level5']),
}

# Route files that are shared infrastructure — stay in database/routes/.
KEEP_IN_PLACE = {'auth', 'dashboard', 'journal', 'tax_codes', 'lookups',
                 'bp', 'shared', 'items', 'buyers', 'coa_seed_data',
                 'Migrationwarehousesdepartments', '__init__'}

STD_CHILD_FILES = ['form.html', 'list.html', 'view.html', 'create.html',
                   'edit.html', 'print.html', 'report.html']
STD_CHILD_PY    = ['api.py', 'service.py', 'validation.py']


def child_html_stub(area, child, kind):
    title = f"{area}/{child}".replace('_', ' ').title()
    return f"""{{% extends 'base.html' %}}
{{% block title %}}{title} — {kind.title()}{{% endblock %}}
{{% block content %}}
<div class=\"container-fluid py-3\">
  <h3 class=\"mb-3\">{title} — {kind.title()}</h3>
  {{# TODO: {kind} view for {area}.{child}. Boilerplate stub generated by reorganize.py. #}}
  <div class=\"alert alert-secondary\">
    Placeholder <strong>{kind}</strong> template for <code>{area}/{child}</code>.
  </div>
</div>
{{% endblock %}}
"""

def api_stub(area, child):
    return f'''"""API endpoints for {area}.{child} (JSON).

Generated stub. Register on the area blueprint in routes.py, e.g.:
    from .api import register_{child}_api
    register_{child}_api(bp)
"""
from flask import jsonify


def register_{child}_api(bp):
    @bp.route("/api/{child}", endpoint="{child}_api_list")
    def _{child}_api_list():
        return jsonify(data=[], module="{area}", child="{child}")
'''

def service_stub(area, child):
    return f'''"""Business-logic layer for {area}.{child}.

Keep DB queries and domain rules here; keep routes.py thin.
Generated stub.
"""


class {to_camel(child)}Service:
    """Service methods for {area}.{child}."""

    @staticmethod
    def list_all():
        raise NotImplementedError

    @staticmethod
    def get(obj_id):
        raise NotImplementedError

    @staticmethod
    def create(data):
        raise NotImplementedError

    @staticmethod
    def update(obj_id, data):
        raise NotImplementedError

    @staticmethod
    def delete(obj_id):
        raise NotImplementedError
'''

def validation_stub(area, child):
    return f'''"""Validation helpers for {area}.{child}.

Return a list of error strings; empty list == valid. Generated stub.
"""


def validate_{child}(data: dict) -> list[str]:
    errors: list[str] = []
    # TODO: add field checks for {area}.{child}
    return errors
'''

def to_camel(s):
    return ''.join(p.capitalize() for p in s.split('_'))


def backup():
    dest = os.path.join(ROOT, '_backup_before_reorg')
    if os.path.exists(dest):
        log('  backup already exists — skipping'); return
    if DRY:
        log('  [dry] would back up app.py, database/, templates/'); return
    os.makedirs(dest)
    for item in ['app.py', 'database', 'templates']:
        src = os.path.join(ROOT, item)
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(dest, item))
        elif os.path.isfile(src):
            shutil.copy2(src, os.path.join(dest, item))
    log('  backup written to _backup_before_reorg/')


def ensure(path):
    if DRY:
        return
    os.makedirs(path, exist_ok=True)

def write(path, content, overwrite=False):
    if os.path.exists(path) and not overwrite:
        return
    if DRY:
        log(f'    [dry] write {os.path.relpath(path, ROOT)}'); return
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)


def build_modules():
    modules_root = os.path.join(ROOT, 'modules')
    ensure(modules_root)
    write(os.path.join(modules_root, '__init__.py'), '', overwrite=True)

    for area, cfg in AREAS.items():
        adir = os.path.join(modules_root, area)
        ensure(adir)
        write(os.path.join(adir, '__init__.py'),
              f'"""{area} module package."""\n', overwrite=True)

        # templates/<tpl_subdir>/  — copy existing templates so per-bp
        # template_folder resolves the SAME relative paths as before.
        tpl_root = os.path.join(adir, 'templates')
        ensure(tpl_root)
        for sub in cfg['tpl_subdirs']:
            src = os.path.join(ROOT, 'templates', sub)
            dst = os.path.join(tpl_root, sub)
            if os.path.isdir(src):
                if DRY:
                    log(f'    [dry] copy templates/{sub} -> modules/{area}/templates/{sub}')
                else:
                    if not os.path.exists(dst):
                        shutil.copytree(src, dst)

        # per-child spec folders + standard file set
        for child in cfg['children']:
            cdir = os.path.join(tpl_root, area, child) if False else \
                   os.path.join(adir, 'children', child)
            ensure(cdir)
            for fn in STD_CHILD_FILES:
                kind = fn.replace('.html', '')
                write(os.path.join(cdir, fn), child_html_stub(area, child, kind))
            write(os.path.join(cdir, 'api.py'),        api_stub(area, child))
            write(os.path.join(cdir, 'service.py'),    service_stub(area, child))
            write(os.path.join(cdir, 'validation.py'), validation_stub(area, child))
            write(os.path.join(cdir, '__init__.py'), '', overwrite=True)

        # area-level service/validation/api stubs
        write(os.path.join(adir, 'service.py'),
              f'"""Area-level service aggregation for {area}."""\n')
        write(os.path.join(adir, 'validation.py'),
              f'"""Area-level validation for {area}."""\n')
        write(os.path.join(adir, 'api.py'),
              f'"""Area-level JSON API for {area}."""\n')

        log(f'  built modules/{area}/  '
            f'({len(cfg["children"])} children, '
            f'{len(cfg["tpl_subdirs"])} template dirs)')


if __name__ == '__main__':
    log('== Seller-MS reorganization ==', '(DRY RUN)' if DRY else '')
    log('[1/2] backup')
    backup()
    log('[2/2] build modules/ tree')
    build_modules()
    log('DONE.' + (' (dry — nothing written)' if DRY else ''))
