"""add warehousee for seller

Revision ID: 94a40140de6c
Revises: a3414307065d
Create Date: 2026-07-04 15:18:53.164918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a40140de6c'
down_revision = 'a3414307065d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_warehouse_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('location_name_ar', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_name', sa.String(length=200), nullable=False),
    sa.Column('warehouse_name_ar', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['seller_warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('warehouse_locations')
    op.drop_table('warehouses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('warehouse_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('warehouse_name_ar', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['warehouse_locations.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('location_name_ar', sa.VARCHAR(length=150), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('seller_warehouses')
    op.drop_table('seller_warehouse_locations')
    # ### end Alembic commands ###
