"""add warehouses, departments, locations, buyer salary_order

Revision ID: a3414307065d
Revises: 4bbf9aa7bd03
Create Date: 2026-07-04 15:14:29.402946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3414307065d'
down_revision = '4bbf9aa7bd03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer_department_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=150), nullable=False),
    sa.Column('location_name_ar', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buyer_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('department_name', sa.String(length=200), nullable=False),
    sa.Column('department_name_ar', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['buyer_department_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('department_locations')
    op.drop_table('departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('buyer_id', sa.INTEGER(), nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('department_name_ar', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['department_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('location_name_ar', sa.VARCHAR(length=150), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('buyer_departments')
    op.drop_table('buyer_department_locations')
    # ### end Alembic commands ###
